#ifndef MARKVIEW_CONSTANTS_H
#define MARKVIEW_CONSTANTS_H


#define MARKVIEW_PROGRAM_NAME "markview"
#define MARKVIEW_TITLE_SEPARATOR " - "
#define MARKVIEW_FILENAME_EMPTY_FILE "Welcome"
#define MARKVIEW_WINDOW_DEFAULT_WIDTH 900
#define MARKVIEW_WINDOW_DEFAULT_HEIGHT 600
#define MARKVIEW_SETTINGS_FILE_NAME "settings.json"
#define MARKVIEW_CMARK_OPTIONS CMARK_OPT_DEFAULT | CMARK_OPT_FOOTNOTES | CMARK_OPT_UNSAFE
#define MARKVIEW_SDL_DEFAULT_WINDOW_SIZE SDL_WINDOW_RESIZABLE

#endif // MARKVIEW_CONSTANTS_H
