name: Snapshot
on:
  workflow_dispatch:
jobs:
  snapshot:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: Setup C/C++ Compiler
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: gcc-latest
      - name: Create build folder
        run: mkdir build
      - name: Run cmake
        working-directory: build
        run: cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
      - name: Run make
        working-directory: ./build
        run: make markview
      - name: Generate time
        id: get-time
        shell: powershell
        run: |
          $timestamp = Get-Date -Format "yyyy-MM-ddTHHmmss"
          Write-Output TIME=$timestamp >> $env:GITHUB_OUTPUT
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TIME: ${{ steps.get-time.outputs.TIME }}
          TITLE: markview ${{ steps.get-time.outputs.TIME }} snapshot
        working-directory: ./build
        shell: powershell
        run: |
          gh release create ${{ env.TIME }} --title="${{ env.TITLE }}" markview.exe
