name: Snapshot
on:
  workflow_dispatch:
jobs:
  snapshot:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: Setup C/C++ Compiler
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: gcc-latest
      - name: Create build folder
        run: mkdir build
      - name: Run cmake
        working-directory: build
        run: cmake .. -G "MinGW Makefiles"
      - name: Run make
        working-directory: ./build
        run: make markview
      - name: Create release
        working-directory: ./build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create ${{ steps.date.outputs.date }} --title=${{ steps.date.outputs.date }} markview.exe